### ISSUE TITLE
bug: `pnpm i` doesnt install `@acme/api`

### ISSUE THREAD

**Issue by violetbee** [t3-oss/create-t3-turbo#83] opened 2022-11-26 11:01 UTC
![image](https://user-images.githubusercontent.com/61601796/204085437-87810d89-8665-4f64-a6dd-2e97f187257d.png)

the other packages are okay

**Comment by juliusmarminge** [comment] 2022-11-26 14:34
Where's this error?

**Comment by violetbee** [comment] 2022-11-26 14:36
![image](https://user-images.githubusercontent.com/61601796/204094249-c16e14c2-1ea4-43ee-827c-0c51aaad4c3f.png)

**Comment by juliusmarminge** [comment] 2022-11-26 14:40
Works on my end

https://user-images.githubusercontent.com/51714798/204094449-f61276c2-2e0e-4cda-8628-a5e0910c1282.mp4

**Comment by juliusmarminge** [comment] 2022-11-26 14:43
https://user-images.githubusercontent.com/51714798/204094619-13537a24-2686-40fe-a245-43d883e4d1bf.mp4

After a clean install

**Comment by violetbee** [comment] 2022-11-26 14:45
> CleanShot.2022-11-26.at.15.43.02.mp4 
> After a clean install

I dont know what is happening, I have tried for 3 times, cloning repo and then pnpm i. nothing different

**Comment by violetbee** [comment] 2022-11-26 14:51
I have checked node_modules and couldnt find folder like @acme

**Comment by juliusmarminge** [comment] 2022-11-26 15:14
This is my node_modules in the expo app

<img width="324" alt="CleanShot 2022-11-26 at 16 14 26@2x" src="https://user-images.githubusercontent.com/51714798/204095925-276ce00c-beb9-4d3b-bbbf-bd6febc85edb.png">

What pnpm version are you on?

**Comment by violetbee** [comment] 2022-11-26 15:15
node v16.16, pnpm v7.17.0

**Comment by violetbee** [comment] 2022-11-26 15:20
I was thinking that pnpm would automatically install dependencies directly from the yaml file. I had to pnpm all the folders one by one, that way there is no problem.

**Comment by juliusmarminge** [comment] 2022-11-26 17:04
> I was thinking that pnpm would automatically install dependencies directly from the yaml file. I had to pnpm i all the folders one by one, that way there is no problem.

That's really strange, should work no matter where you install

**Comment by violetbee** [comment] 2022-11-26 17:06
> > I was thinking that pnpm would automatically install dependencies directly from the yaml file. I had to pnpm i all the folders one by one, that way there is no problem.
> 
> That's really strange, should work no matter where you install

Actually I am still having issue :)
![image](https://user-images.githubusercontent.com/61601796/204100453-a8dc5703-44b6-4e35-bb59-648c8848a00f.png)

**Comment by juliusmarminge** [comment] 2022-11-26 17:08
Have you tried making a clean install and see if it's there on a new project too?

I am not sure what else you can do. I can't reproduce this on my end

**Comment by violetbee** [comment] 2022-11-26 17:10
> 

Yes, that one was the exact same create-t3-turbo clone, I am going to try it on macos later. I have tried atleast :D

**Comment by violetbee** [comment] 2022-11-26 17:20
> > I was thinking that pnpm would automatically install dependencies directly from the yaml file. I had to pnpm i all the folders one by one, that way there is no problem.
> 
> That's really strange, should work no matter where you install

And I wanted to add something more, It only skips "link:" folders while installing with pnpm i

**Comment by soya-miruku** [comment] 2022-11-27 05:28
I wonder if this is a vscode issue, might sound retarded, but I had a similar issue as I am on Linux, but if you do cntrl + shift + p then search reload and do a dev reload window, might work. Again I'm just throwing other ideas @violetbee

**Comment by violetbee** [comment] 2022-11-27 08:27
> I wonder if this is a vscode issue, might sound retarded, but I had a similar issue as I am on Linux, but if you do cntrl + shift + p then search reload and do a dev reload window, might work. Again I'm just throwing other ideas @violetbee

It didnt work for me :D

**Comment by teddybee** [comment] 2022-11-30 14:23
@violetbee Are you using Windows? Could you check if a turbo.exe exists  somewhere in your node_modules dir after pnpm i?

**Comment by violetbee** [comment] 2022-11-30 15:09
@teddybee I am using window's default antivrus program and there is not turbo.exe inside node_modules dir after pnpm i

**Comment by teddybee** [comment] 2022-11-30 16:10
@violetbee That means, the turborepo's exe is moved to quarantine. 
Try to update your antivirus, remove your node modules and do pnpm i again. 
This helped for me.

**Comment by violetbee** [comment] 2022-11-30 20:15
@teddybee I double checked and there is a turbo.exe, antivirus program didnt move quarantine the exe file

**Comment by msasen** [comment] 2022-12-02 07:34
<img width="979" alt="image" src="https://user-images.githubusercontent.com/29780691/205239509-22002be2-534e-4d09-b04a-664e94d0b64a.png">
I have the same problem.
device:m1 mac

**Comment by violetbee** [comment] 2022-12-02 09:47
Same with me, I tried cloning the project to mac air m1 and then did [pnpm i]. The linked packages are still not installed.

**Comment by juliusmarminge** [comment] 2022-12-05 01:08
Still can't reproduce this. Here's a clip where I clone and init locally: https://share.cleanshot.com/aXuxQv.

node_modules still containing the api:

<img width="230" alt="CleanShot 2022-12-05 at 02 07 50@2x" src="https://user-images.githubusercontent.com/51714798/205528116-3eaa6e07-d7c6-494e-a63b-bbba3a432ff7.png">

<img width="236" alt="CleanShot 2022-12-05 at 02 08 35@2x" src="https://user-images.githubusercontent.com/51714798/205528135-c8363379-9730-4a2e-b9ea-1146d41c7a89.png">

**Comment by juliusmarminge** [comment] 2022-12-05 01:10
Oh I'm also on Mac btw:

```
  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 307.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    typescript: ^4.9.3 => 4.9.3
```

**Comment by juliusmarminge** [comment] 2022-12-05 19:59
> This is really interesting.
> 
> https://youtu.be/eCh2G9AQyjs  
> 
> 
> 
> $ pnpm -v
> 
> 7.17.0
> 
> device: mac m1.
> 
> 
> 
> > Oh I'm also on Mac btw:
> 
> > 
> 
> > ```
> 
> >   System:
> 
> >     OS: macOS 13.0.1
> 
> >     CPU: (8) arm64 Apple M1 Pro
> 
> >     Memory: 307.55 MB / 16.00 GB
> 
> >     Shell: 5.8.1 - /bin/zsh
> 
> >   Binaries:
> 
> >     Node: 18.11.0 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/node
> 
> >     npm: 8.19.2 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/npm
> 
> >   Browsers:
> 
> >     Chrome: 108.0.5359.94
> 
> >     Firefox: 107.0
> 
> >     Safari: 16.1
> 
> >   npmPackages:
> 
> >     typescript: ^4.9.3 => 4.9.3
> 
> > ```
> 
> > 
> 
> > ```
> 
> > $ pnpm -v
> 
> > 7.17.0
> 
> > ```
> 
> 
> 
> 

Vid's private

**Comment by msasen** [comment] 2022-12-06 06:08
> > This is really interesting.
> > https://youtu.be/eCh2G9AQyjs
> > $ pnpm -v
> > 7.17.0
> > device: mac m1.
> > > Oh I'm also on Mac btw:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > System:
> > 
> > 
> > > ```
> > > OS: macOS 13.0.1
> > > ```
> > 
> > 
> > > ```
> > > CPU: (8) arm64 Apple M1 Pro
> > > ```
> > 
> > 
> > > ```
> > > Memory: 307.55 MB / 16.00 GB
> > > ```
> > 
> > 
> > > ```
> > > Shell: 5.8.1 - /bin/zsh
> > > ```
> > 
> > 
> > > Binaries:
> > 
> > 
> > > ```
> > > Node: 18.11.0 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/node
> > > ```
> > 
> > 
> > > ```
> > > npm: 8.19.2 - ~/Library/Caches/fnm_multishells/78534_1670065369368/bin/npm
> > > ```
> > 
> > 
> > > Browsers:
> > 
> > 
> > > ```
> > > Chrome: 108.0.5359.94
> > > ```
> > 
> > 
> > > ```
> > > Firefox: 107.0
> > > ```
> > 
> > 
> > > ```
> > > Safari: 16.1
> > > ```
> > 
> > 
> > > npmPackages:
> > 
> > 
> > > ```
> > > typescript: ^4.9.3 => 4.9.3
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > $ pnpm -v
> > 
> > 
> > > 7.17.0
> > 
> > 
> > >
> 
> Vid's private
Ok. I fixed it
https://youtu.be/eCh2G9AQyjs

**Comment by lutfi-haslab** [comment] 2023-01-02 15:44
> 

hey thank you, my problem is not @acme/api but @acme/db. after reload my vs code, now its working no error.

**Comment by juliusmarminge** [comment] 2023-01-02 17:13
> > 
> 
> 
> 
> hey thank you, my problem is not @acme/api but @acme/db. after reload my vs code, now its working no error.

All i can think off is that you have some global pnpm settings that make this happen

**Comment by violetbee** [comment] 2023-01-17 09:29
@juliusmarminge hey julius, did you find any solution? I wanted to use turbo on my main t3 project

**Comment by juliusmarminge** [comment] 2023-01-17 09:31
> @juliusmarminge hey julius, did you find any solution? I wanted to use turbo on my main t3 project

It works on my machine every time so I don't know what's wrong - and also hard to test any "solution"...

**Comment by violetbee** [comment] 2023-01-17 09:32
> > @juliusmarminge hey julius, did you find any solution? I wanted to use turbo on my main t3 project
> 
> It works on my machine every time so I don't know what's wrong - and also hard to test any "solution"...
> 
> the `@acme/db` doesn't get any node_modules since we hoist prisma but that shouldn't be a problem


I'll go over this a bit, if I find a solution I'll share it.

**Comment by jjrise** [comment] 2023-02-01 04:14
@violetbee did you have any resolution here?

**Comment by zmzlois** [comment] 2023-02-06 00:04
I have the same issue too. ```pnpm i``` have never worked on my laptop, I am on 
Mac M1
```
pnpm -v
7.26.2
```

**Comment by jjrise** [comment] 2023-02-06 00:57
> I have the same issue too. acme is already installed but the files seems fail to locate where acme is and can't recognize `@acme/api` and `@acme/db` I am using the t3-clerk-expo one atm but it same issue. `pnpm i` have never worked on my laptop, I am on Mac M1
> 
> ```
> pnpm -v
> 7.26.2
> ```
> 
> Every time I run `pnpm i` it shows this but when I run `pnpm` to check global setting it looks fine. It's affecting the OSS projects I want to contribute to so bad ![Screenshot 2023-02-06 at 00 04 56](https://user-images.githubusercontent.com/79988376/216854146-00bcf09d-1391-4da5-aac4-e8e360a3661e.png)

We were discussing something similar in a different thread. But upgrading pnpm / turbo / node worked for us.

**Comment by juliusmarminge** [comment] 2023-02-06 08:32
> I have the same issue too. 
> 
> acme is already installed but the files seems fail to locate where acme is and can't recognize `@acme/api` and `@acme/db` 
> 
> I am using the t3-clerk-expo one atm but it same issue.
> 
> ```pnpm i``` have never worked on my laptop, I am on 
> 
> Mac M1
> 
> ```
> 
> pnpm -v
> 
> 7.26.2
> 
> ```
> 
> Every time I run `pnpm i` it shows this but when I run `pnpm` to check global setting it looks fine. It's affecting the OSS projects I want to contribute to so bad
> 
> ![Screenshot 2023-02-06 at 00 04 56](https://user-images.githubusercontent.com/79988376/216854146-00bcf09d-1391-4da5-aac4-e8e360a3661e.png)
> 
> 

This seems like another issue? Mind sharing a bigger chunk of the logs?

**Comment by yemirhan** [comment] 2023-02-11 18:22
This happened to a few friends of mine, and we found out the fix of this problem is to cd into apps/nextjs and expo and run pnpm i in there. Maybe that would be the fix for this problem

**Comment by zmzlois** [comment] 2023-02-18 18:01
> > I have the same issue too. acme is already installed but the files seems fail to locate where acme is and can't recognize `@acme/api` and `@acme/db` I am using the t3-clerk-expo one atm but it same issue. `pnpm i` have never worked on my laptop, I am on Mac M1
> > ```
> > pnpm -v
> > 7.26.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Every time I run `pnpm i` it shows this but when I run `pnpm` to check global setting it looks fine. It's affecting the OSS projects I want to contribute to so bad ![Screenshot 2023-02-06 at 00 04 56](https://user-images.githubusercontent.com/79988376/216854146-00bcf09d-1391-4da5-aac4-e8e360a3661e.png)
> 
> We were discussing something similar in a different thread. But upgrading pnpm / turbo / node worked for us.

where is the other thread?

**Comment by zmzlois** [comment] 2023-02-19 18:26
Finally fixed this. 
Turns out it was a pnpm issue, I am on 
```
Mac Chip Apple M1
OS Ventura 13.2.1
node -v
v18.13.0
```
What I did to fix it: 

High chance I accidently installed pnpm with different package managers and different commands way back in time and it is confusing my system and it didn't know where all the installation should go so it shows me `ENOENT: no such file or directory, mkdir '/path',  So prob a fresh start would help.

1. I tried to remove pnpm by `npm rm pnpm` and `brew rm pnpm` but it didn't solve the problem.
2. I ran `pnpm add -g pnpm` to see if current location and target location are different and apparently there were two different paths.
3. Check `whereis pnpm` and it was in `/Users/lois/.nvm/versions/node/v18.13.0/bin` so I went in to delete everything related to pnpm in there including `pnpm` and `pnpx`
4. And I check `whereis pnpm` again and there is another one in `/Users/lois/Library/pnpm` so I went in to delete them there too
5. Then I check my path variable with `echo $PATH` and it was showing me pnpm pointed towards /Users/lois/.nvm/versions/node/v18.13.0/bin` so I went to `.zshrc` to delete the record and also check `.zprofile`, `bash_profile` and also passby `.npmrc` to see if anything fishy and deleted everything related to pnpm
6. Download pnpm again by `curl -fsSL https://get.pnpm.io/install.sh | sh -` and then `source /Users/lois/.zshrc` 
7. Went back into t3-turbo and also the clerk-t3-expo dir terminal and now`pnpm install` works as well as all the dependencies like @acme/db @acme/api etc

But still got some questions: 

- I was reading [turborepo documentation](https://turbo.build/repo/docs/handbook/workspaces#workspaces-which-depend-on-each-other) I thought if package manager is pnpm we should specify the dependencies with "workspace:*"? 

- And why are we naming them @acme/api but not @package/api?

**Comment by juliusmarminge** [comment] 2023-02-19 18:31
> I was reading [turborepo documentation](https://turbo.build/repo/docs/handbook/workspaces#workspaces-which-depend-on-each-other) I thought if package manager is pnpm we should specify the dependencies with "workspace:*"?

Yea that'd be good but it's not supported by `manypkg` and I think that brings a lot of value: https://github.com/Thinkmill/manypkg/issues/147

> And why are we naming them @acme/api but not @package/api?

You'd prob put your compnay/project name there instead. acme is just a generic name: https://en.wikipedia.org/wiki/Acme_Corporation

**Comment by zmzlois** [comment] 2023-02-19 18:35
> > I was reading [turborepo documentation](https://turbo.build/repo/docs/handbook/workspaces#workspaces-which-depend-on-each-other) I thought if package manager is pnpm we should specify the dependencies with "workspace:*"?
> 
> Yea that'd be good but it's not supported by `manypkg` and I think that brings a lot of value: [Thinkmill/manypkg#147](https://github.com/Thinkmill/manypkg/issues/147)
> 
> > And why are we naming them @acme/api but not @package/api?
> 
> You'd prob put your compnay/project name there instead. acme is just a generic name: https://en.wikipedia.org/wiki/Acme_Corporation

YOU = OSS BEAST 🔥

**Comment by violetbee** [comment] 2023-02-19 18:39
> Finally fixed this. 
> 
> Turns out it was a pnpm issue, I am on 
> 
> ```
> 
> Mac Chip Apple M1
> 
> OS Ventura 13.2.1
> 
> node -v
> 
> v18.13.0
> 
> ```
> 
> What I did to fix it: 
> 
> 
> 
> High chance I accidently installed pnpm with different package managers with different commands way back in time and it is confusing my system and it didn't know where all the installation should go so it shows me `ENOENT: no such file or directory, mkdir '/path'`,  So prob a fresh start would help.
> 
> 
> 
> 1. I tried to remove pnpm by `npm rm pnpm` and `brew rm pnpm` but it didn't solve the problem.
> 
> 2. I ran `pnpm add -g pnpm` to see if current location and target location are different and apparently there were two different paths.
> 
> 3. Check `whereis pnpm` and it was in `/Users/lois/.nvm/versions/node/v18.13.0/bin` so I went in to delete everything related to pnpm in there including `pnpm` and `pnpx`
> 
> 4. And I check `whereis pnpm` again and there is another one in `/Users/lois/Library/pnpm` so I went in to delete them there too
> 
> 5. Then I check my path variable with `echo $PATH` and it was showing me pnpm pointed towards `/Users/lois/.nvm/versions/node/v18.13.0/bin` so I went to `.zshrc` to delete the record and also check `.zprofile`, `bash_profile` and also passby `.npmrc` to see if anything fishy and deleted everything related to pnpm
> 
> 6. Download pnpm again by `curl -fsSL https://get.pnpm.io/install.sh | sh -` and then `source /Users/lois/.zshrc` 
> 
> 7. Went back into t3-turbo and also the clerk-t3-expo dir terminal and now`pnpm install` works as well as all the dependencies like @acme/db @acme/api etc
> 
> 
> 
> But still got some questions: 
> 
> 
> 
> - I was reading [turborepo documentation](https://turbo.build/repo/docs/handbook/workspaces#workspaces-which-depend-on-each-other) I thought if package manager is pnpm we should specify the dependencies with "workspace:*"? 
> 
> 
> 
> - And why are we naming them @acme/api but not @package/api?

I am going to try it, thanks btw

**Comment by zmzlois** [comment] 2023-02-19 23:49
> > Finally fixed this.
> > Turns out it was a pnpm issue, I am on
> > ```
> > 
> > Mac Chip Apple M1
> > 
> > OS Ventura 13.2.1
> > 
> > node -v
> > 
> > v18.13.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What I did to fix it:
> > High chance I accidently installed pnpm with different package managers with different commands way back in time and it is confusing my system and it didn't know where all the installation should go so it shows me `ENOENT: no such file or directory, mkdir '/path'`,  So prob a fresh start would help.
> > 
> > 1. I tried to remove pnpm by `npm rm pnpm` and `brew rm pnpm` but it didn't solve the problem.
> > 2. I ran `pnpm add -g pnpm` to see if current location and target location are different and apparently there were two different paths.
> > 3. Check `whereis pnpm` and it was in `/Users/lois/.nvm/versions/node/v18.13.0/bin` so I went in to delete everything related to pnpm in there including `pnpm` and `pnpx`
> > 4. And I check `whereis pnpm` again and there is another one in `/Users/lois/Library/pnpm` so I went in to delete them there too
> > 5. Then I check my path variable with `echo $PATH` and it was showing me pnpm pointed towards `/Users/lois/.nvm/versions/node/v18.13.0/bin` so I went to `.zshrc` to delete the record and also check `.zprofile`, `bash_profile` and also passby `.npmrc` to see if anything fishy and deleted everything related to pnpm
> > 6. Download pnpm again by `curl -fsSL https://get.pnpm.io/install.sh | sh -` and then `source /Users/lois/.zshrc`
> > 7. Went back into t3-turbo and also the clerk-t3-expo dir terminal and now`pnpm install` works as well as all the dependencies like @acme/db @acme/api etc
> > 
> > But still got some questions:
> > 
> > * I was reading [turborepo documentation](https://turbo.build/repo/docs/handbook/workspaces#workspaces-which-depend-on-each-other) I thought if package manager is pnpm we should specify the dependencies with "workspace:*"?
> > * And why are we naming them @acme/api but not @package/api?
> 
> I am going to try it, thanks btw

if you haven't been able to locate @acme/api, check your `pnpm-lock.yaml` at root dir whether the package is hard linked within this file, naming the `api` file under `packages` might be causing some confusion as there are `acme` packages exist on npm but the `@acme/api` here refer to the `api` file in `packages`. 

See if these lines exist in your `pnpm-lock.yaml`:
```
 apps/expo:
    specifiers:
      '@acme/api': '*'
.....
    dependencies:
       '@acme/api': link:../../packages/api
``` 
same goes to `apps/nextjs` if you couldn't locate `@acme/api` in there too
and in root dir you should have a `pnpm-workspace.yaml` exist to specify your workplace, refer to [this](https://turbo.build/repo/docs/handbook/workspaces#configuring-workspaces) again

**Comment by juliusmarminge** [comment] 2023-05-07 20:25
no activity on this for a while - anyone still facing this issue feel free to ping me here or reopen a new one

**Closed by juliusmarminge** 2023-05-07 20:25 UTC
Labels: help wanted, unable to reproduce
