### ISSUE TITLE
bug: can't build expo for ios

### ISSUE THREAD

**Issue by mateuszkoncikowski** [t3-oss/create-t3-turbo#99] opened 2022-12-29 19:40 UTC
Hi, really like the t3 approach here and I'm playing with the template the whole day. 

I'm having issues with building this on Expo. 
Cloned the repo. Everything works locally. I'm trying to create my first build on expo with this:  
` eas build --platform ios --profile preview`
The build is triggered correctly but it fails on Fastlane step with this error message:

`error: Could not determine react-native-codegen location in /Users/expo/workingdir/build/apps/expo/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../packages/react-native-codegen or /Users/expo/workingdir/build/apps/expo/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../../react-native-codegen. Try running 'yarn install' or 'npm install' in your project root.` 

To me it seems that the issue is connected with how dependencies are are solved via pnpm (never used this manager before).

After doing `pnpm i` `react-native-codegen` is located in the root project `node_modules` not in `apps/expo/node_modules`. 

Can anyone assist me here? ;-)

**Comment by mateuszkoncikowski** [comment] 2022-12-29 19:41
Tried to add `react-native-codegen` as dependency in `apps/expo/package.json` as a workaround but this didn't work and it's an ugly workaround in the first place.

**Comment by juliusmarminge** [comment] 2022-12-29 20:33
I don't have a paid Apple Dev account at this time so can't test this myself unfortunately.

Check this page out: https://docs.expo.dev/guides/monorepos/#common-issues

It goes over some of the common issues with monorepos and dependency resolving.

**Comment by mateuszkoncikowski** [comment] 2022-12-30 07:59
you can build a simulator version without the apple developer account, just use this `eas.json`:
`{
  "cli": {
    "version": ">= 3.1.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "ios": {
        "simulator": true
      },
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}`

and run `eas build --platform ios --profile preview`

I've also checked this package from vercel https://github.com/vercel/turbo/tree/main/examples/with-react-native-web which is simpler nextjs + rn setup based on yarn and the issue is reproducible there too (locally everything works as expected).

The whole thing is connected to the monorepo concept and how the RN dependencies are managed.

At the same time, I'm a bit confused because this would mean that using this template no one is able to build an actual ios package on expo 🤷🏻 

Would be awesome if more eyeballs 👁️ could look into this issue.

**Comment by juliusmarminge** [comment] 2022-12-30 08:22
I know for a fact that people have gotten successful builds with this and some even applied to the App Store.

Will look further into this later today

**Comment by juliusmarminge** [comment] 2022-12-30 09:06
Update 1: I got a build running but failed at the end due to my Xcode being out of date so something there failed. Didn't have any npm issues though, maybe that'll show later.

Updating XCode now, will get back once done

**Comment by mateuszkoncikowski** [comment] 2022-12-30 09:15
🤔 

i'm not sure how your local setup (outdated xcode) connects to the issue

the build is being executed on a remote machine via expo build service, and that's the place where the issue occurs 

![CleanShot 2022-12-30 at 10 13 26](https://user-images.githubusercontent.com/4365080/210053884-0044001d-3389-448c-9401-4864e771a913.png)
![CleanShot 2022-12-30 at 10 15 12](https://user-images.githubusercontent.com/4365080/210054009-fa687a21-7865-4ead-97fc-12449725dc69.png)

**Comment by juliusmarminge** [comment] 2022-12-30 10:04
You're right, misinterpreted the error and found the same error as you had further down...

Experimented a bit with different versions etc but couldn't get it working... maybe @byCedric have some insights 👀

**Comment by chen-rn** [comment] 2023-01-02 21:31
> 🤔
> 
> i'm not sure how your local setup (outdated xcode) connects to the issue
> 
> the build is being executed on a remote machine via expo build service, and that's the place where the issue occurs
> 
> ![CleanShot 2022-12-30 at 10 13 26](https://user-images.githubusercontent.com/4365080/210053884-0044001d-3389-448c-9401-4864e771a913.png) ![CleanShot 2022-12-30 at 10 15 12](https://user-images.githubusercontent.com/4365080/210054009-fa687a21-7865-4ead-97fc-12449725dc69.png)

Were you able to find a solution to this @mateuszkoncikowski ?

**Comment by hasanjafri** [comment] 2023-01-07 11:37
Hey guys @mateuszkoncikowski @juliusmarminge

I tried playing around with the repo as well to try to make a successful iOS build. After experimenting with some builds, it seems that this error occurs while using Expo SDK 47 but I don't know why yet.

But luckily I have an app that uses SDK 46 and is already in the stores, I want to migrate our stack to the t3-turbo stack. So I tried to downgrade the dependencies in the expo app to work with SDK 46 and I got the iOS build to succeed. 

Here is my commit with these changes: https://github.com/t3-oss/create-t3-turbo/commit/dfd04a4a5c83ba21a2de2891d5e5aa6dd030cb88

I'm happy to make a PR for this repo as well but I'm not sure if this is necessarily the solution as it should work with SDK 47 as well. But in the meantime for the people trying to use this template to make their own builds and experiment, it can unblock them.

Thanks to all of you guys for the wonderful work on display here 😄 and keep it up!

**Comment by juliusmarminge** [comment] 2023-01-07 11:39
> Hey guys @mateuszkoncikowski @juliusmarminge
> 
> I tried playing around with the repo as well to try to make a successful iOS build. After experimenting with some builds, it seems that this error occurs while using Expo SDK 47 but I don't know why yet.
> 
> But luckily I have an app that uses SDK 46 and is already in the stores, I want to migrate our stack to the t3-turbo stack. So I tried to downgrade the dependencies in the expo app to work with SDK 46 and I got the iOS build to succeed.
> 
> Here is my commit with these changes: [dfd04a4](https://github.com/t3-oss/create-t3-turbo/commit/dfd04a4a5c83ba21a2de2891d5e5aa6dd030cb88)
> 
> I'm happy to make a PR for this repo as well but I'm not sure if this is necessarily the solution as it should work with SDK 47 as well. But in the meantime for the people trying to use this template to make their own builds and experiment, it can unblock them.
> 
> Thanks to all of you guys for the wonderful work on display here 😄 and keep it up!

Interesting find!

Is is something with Expo 47 + PNPM then which is the problem? Cause I assume this isn't an issue for every Expo 47 app or else they would have fixed it quickly?

**Comment by hasanjafri** [comment] 2023-01-07 12:11
> > Hey guys @mateuszkoncikowski @juliusmarminge
> > I tried playing around with the repo as well to try to make a successful iOS build. After experimenting with some builds, it seems that this error occurs while using Expo SDK 47 but I don't know why yet.
> > But luckily I have an app that uses SDK 46 and is already in the stores, I want to migrate our stack to the t3-turbo stack. So I tried to downgrade the dependencies in the expo app to work with SDK 46 and I got the iOS build to succeed.
> > Here is my commit with these changes: [dfd04a4](https://github.com/t3-oss/create-t3-turbo/commit/dfd04a4a5c83ba21a2de2891d5e5aa6dd030cb88)
> > I'm happy to make a PR for this repo as well but I'm not sure if this is necessarily the solution as it should work with SDK 47 as well. But in the meantime for the people trying to use this template to make their own builds and experiment, it can unblock them.
> > Thanks to all of you guys for the wonderful work on display here 😄 and keep it up!
> 
> Interesting find!
> 
> Is is something with Expo 47 + PNPM then which is the problem? Cause I assume this isn't an issue for every Expo 47 app or else they would have fixed it quickly?
> 
> I'm hoping Expo 48 isn't too far out - and with it hopefully react-native 0.71 with full React 18.2 support - will make a lot of stuff much nicer if all versions can be synced... mixing react versions sometimes causes weird issues from my experience...

I'm not sure about the root cause yet but I tried to set up a brand new Expo project separately (with SDK 47) and it was built successfully. I then tried to substitute those exact values for versions in the t3-turbo apps/expo app and that resulted in a failed build with the `react-native-codegen` error. I'll continue to see if I can find a way to work with SDK 47 and paste any updates here.

**Comment by juliusmarminge** [comment] 2023-01-07 12:39
> > > Hey guys @mateuszkoncikowski @juliusmarminge
> 
> > > I tried playing around with the repo as well to try to make a successful iOS build. After experimenting with some builds, it seems that this error occurs while using Expo SDK 47 but I don't know why yet.
> 
> > > But luckily I have an app that uses SDK 46 and is already in the stores, I want to migrate our stack to the t3-turbo stack. So I tried to downgrade the dependencies in the expo app to work with SDK 46 and I got the iOS build to succeed.
> 
> > > Here is my commit with these changes: [dfd04a4](https://github.com/t3-oss/create-t3-turbo/commit/dfd04a4a5c83ba21a2de2891d5e5aa6dd030cb88)
> 
> > > I'm happy to make a PR for this repo as well but I'm not sure if this is necessarily the solution as it should work with SDK 47 as well. But in the meantime for the people trying to use this template to make their own builds and experiment, it can unblock them.
> 
> > > Thanks to all of you guys for the wonderful work on display here 😄 and keep it up!
> 
> > 
> 
> > Interesting find!
> 
> > 
> 
> > Is is something with Expo 47 + PNPM then which is the problem? Cause I assume this isn't an issue for every Expo 47 app or else they would have fixed it quickly?
> 
> > 
> 
> > I'm hoping Expo 48 isn't too far out - and with it hopefully react-native 0.71 with full React 18.2 support - will make a lot of stuff much nicer if all versions can be synced... mixing react versions sometimes causes weird issues from my experience...
> 
> 
> 
> I'm not sure about the root cause yet but I tried to set up a brand new Expo project separately (with SDK 47) and it was built successfully. I then tried to substitute those exact values for versions in the t3-turbo apps/expo app and that resulted in a failed build with the `react-native-codegen` error. I'll continue to see if I can find a way to work with SDK 47 and paste any updates here.

I'd assume it has to do with PNPM+monorepo+Expo.

**Comment by hasanjafri** [comment] 2023-01-07 22:49
> > > > Hey guys @mateuszkoncikowski @juliusmarminge
> > 
> > 
> > > > I tried playing around with the repo as well to try to make a successful iOS build. After experimenting with some builds, it seems that this error occurs while using Expo SDK 47 but I don't know why yet.
> > 
> > 
> > > > But luckily I have an app that uses SDK 46 and is already in the stores, I want to migrate our stack to the t3-turbo stack. So I tried to downgrade the dependencies in the expo app to work with SDK 46 and I got the iOS build to succeed.
> > 
> > 
> > > > Here is my commit with these changes: [dfd04a4](https://github.com/t3-oss/create-t3-turbo/commit/dfd04a4a5c83ba21a2de2891d5e5aa6dd030cb88)
> > 
> > 
> > > > I'm happy to make a PR for this repo as well but I'm not sure if this is necessarily the solution as it should work with SDK 47 as well. But in the meantime for the people trying to use this template to make their own builds and experiment, it can unblock them.
> > 
> > 
> > > > Thanks to all of you guys for the wonderful work on display here 😄 and keep it up!
> > 
> > 
> > > 
> > 
> > 
> > > Interesting find!
> > 
> > 
> > > 
> > 
> > 
> > > Is is something with Expo 47 + PNPM then which is the problem? Cause I assume this isn't an issue for every Expo 47 app or else they would have fixed it quickly?
> > 
> > 
> > > 
> > 
> > 
> > > I'm hoping Expo 48 isn't too far out - and with it hopefully react-native 0.71 with full React 18.2 support - will make a lot of stuff much nicer if all versions can be synced... mixing react versions sometimes causes weird issues from my experience...
> > 
> > 
> > I'm not sure about the root cause yet but I tried to set up a brand new Expo project separately (with SDK 47) and it was built successfully. I then tried to substitute those exact values for versions in the t3-turbo apps/expo app and that resulted in a failed build with the `react-native-codegen` error. I'll continue to see if I can find a way to work with SDK 47 and paste any updates here.
> 
> I'd assume it has to do with PNPM+monorepo+Expo.

Hey, @juliusmarminge you were right, it had to do with PNPM and mono repo:

After doing a bit of research I found this online:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/16377702/211173043-71a466b4-bb0a-434d-97bc-0ee72e485573.png">

So I tried to apply the React-Native@0.70.5 patch myself in my fork of this repo and the iOS build succeeded.

Here is my commit with these changes: https://github.com/hasanjafri/create-t3-turbo/commit/b1f4b4b298f1d4a4ff80fef5aea9d8c84f568fca

All credit for this patch/fix goes to @byCedric (Thanks Cedric!!)

cc @mateuszkoncikowski @chen-rn

**Closed** 2023-01-08 23:04 UTC
Labels: bug, help wanted
