### ISSUE TITLE
bug: Invariant: headers() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by Fralleee** [t3-oss/create-t3-turbo#660] opened 2023-09-29 12:57 UTC
### Provide environment information

System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 15.45 GB / 31.79 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.3 - C:\ProgramData\chocolatey\bin\pnpm.EXE

### Describe the bug

Trying to get the template to run but I am getting errors regarding `headers()`

### Link to reproduction

https://github.com/Fralleee/test-t3-starter

### To reproduce

Follow the default instructions (setup .env e.t.c.) and try running the repo using "dev".

```
@acme/nextjs:dev:   ▲ Next.js 13.5.3
@acme/nextjs:dev:   - Local:        http://localhost:3000
@acme/nextjs:dev:
@acme/nextjs:dev:  ✓ Ready in 2.4s
@acme/nextjs:dev:  ✓ Compiled /page in 1343ms (1294 modules)
@acme/nextjs:dev:  ⨯ Error: Invariant: headers() expects to have requestAsyncStorage, none available.
@acme/nextjs:dev:     at Layout (./src/app/layout.tsx:31:79)
@acme/nextjs:dev:     at stringify (<anonymous>)
@acme/nextjs:dev:  ⨯ Internal error: TypeError: Cannot read properties of undefined (reading '')
@acme/nextjs:dev:     at resolveClientReference (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:40:43)
@acme/nextjs:dev:     at resolveModule (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1825:25)
@acme/nextjs:dev:     at processFullRow (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1900:9)
@acme/nextjs:dev:     at processBinaryChunk (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2048:7)
@acme/nextjs:dev:     at progress (../../node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:2135:5)
@acme/nextjs:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
@acme/nextjs:dev:     at runNextTicks (node:internal/process/task_queues:64:3)
@acme/nextjs:dev:     at listOnTimeout (node:internal/timers:540:9)
@acme/nextjs:dev:     at process.processTimers (node:internal/timers:514:7)
@acme/nextjs:dev: [TypeError: Cannot read properties of undefined (reading '')]
@acme/nextjs:dev: [TypeError: Cannot read properties of undefined (reading '')]
@acme/nextjs:dev: [TypeError: Cannot read properties of null (reading 'default')]
```

**Comment by Fralleee** [comment] 2023-09-29 13:13
I can get it to run if I comment out the following at all places:
```js
    // export const runtime = "edge";
```

**Comment by otomir23** [comment] 2023-10-06 06:54
Same issue!

**Comment by juliusmarminge** [comment] 2023-10-06 07:43
Cannot reproduce: https://app.warp.dev/block/orEYBmUFjvitPCBao1tFAr

But keep in mind that since we use headers() in layout, your app can't be static. If you need that, you should mount the TRPCProvider further down your tree. I'll make a note about this

**Comment by TNSelahle** [comment] 2023-10-11 16:34
Hey, @Fralleee :) Have you found a way around this?

**Comment by Fralleee** [comment] 2023-10-11 19:03
> Hey, @Fralleee :) Have you found a way around this?

As I wrote previously, commenting out these worked:
```
// export const runtime = "edge";
```

But other than I have no idea, unfortunately.

**Comment by matteobad** [comment] 2023-10-26 16:56
I think it's related to this: https://github.com/vercel/next.js/issues/52176
Only on Windows

**Comment by juliusmarminge** [comment] 2023-11-01 22:25
Closing as it doesn't seem to be an issue with anything turbo related

**Closed by juliusmarminge** 2023-11-01 22:25 UTC
Labels: unable to reproduce, hacktoberfest
