### ISSUE TITLE
bug: eas failing development build - iOS simulator

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [t3-oss/create-t3-turbo#402] opened 2023-06-10 00:13 UTC
### Provide environment information

  System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.86 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman

### Describe the bug

trying to run eas development build with `simulator: true` fails

```log
We detected that 'apps/expo' is a pnpm workspace
Running "pnpm install --no-frozen-lockfile" in the root dir of your repository 
WARN  Unsupported engine: wanted: {"node":">=v18.16.0"} (current: {"node":"v16.18.1","pnpm":"7.27.0"})
Scope: all 8 workspace projects
WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 6.0
ERROR  /@alloc/quick-lru@5.2.0 is an invalid relative dependency path
pnpm: /@alloc/quick-lru@5.2.0 is an invalid relative dependency path
    at Object.parse2 [as parse] (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:110878:15)
    at nameVerFromPkgSnapshot (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:110994:28)
    at addPreferredVersionsFromLockfile (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:183708:89)
    at getPreferredVersionsFromLockfileAndManifests (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:183702:7)
    at _installInContext (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:184583:147)
    at async installInContext (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:184898:27)
    at async _install (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:184457:25)
    at async mutateModules (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:184196:23)
    at async recursive (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:185666:29)
    at async installDeps (/Users/expo/.nvm/versions/node/v16.18.1/lib/node_modules/pnpm/dist/pnpm.cjs:185952:11)
pnpm exited with non-zero code: 1
```

my package.json /apps/expo
``` json
{
  "name": "@acme/expo",
  "version": "0.1.0",
  "main": "index.tsx",
  "scripts": {
    "clean": "git clean -xdf .expo .turbo node_modules",
    "dev": "expo start --ios",
    "dev:android": "expo start --android",
    "dev:ios": "expo start --ios",
    "lint": "eslint .",
    "lint:fix": "pnpm lint --fix",
    "type-check": "tsc --noEmit"
  },
  "dependencies": {
    "@expo/metro-config": "^0.7.1",
    "@react-native-async-storage/async-storage": "^1.18.2",
    "@shopify/flash-list": "1.4.3",
    "@tanstack/react-query": "^4.29.5",
    "@trpc/client": "^10.27.1",
    "@trpc/react-query": "^10.27.1",
    "@trpc/server": "^10.27.1",
    "expo": "^48.0.19",
    "expo-application": "~5.1.1",
    "expo-auth-session": "~4.0.3",
    "expo-constants": "~14.2.1",
    "expo-crypto": "~12.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-google-app-auth": "~8.3.0",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.5.3",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-web-browser": "~12.1.1",
    "firebase": "^9.22.2",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.8",
    "react-native-safe-area-context": "4.5.3",
    "react-native-screens": "~3.20.0",
    "superjson": "1.9.1"
  },
  "devDependencies": {
    "@acme/api": "^0.1.0",
    "@acme/auth": "^0.1.0",
    "@acme/eslint-config": "^0.1.0",
    "@acme/tailwind-config": "^0.1.0",
    "@babel/core": "^7.21.8",
    "@babel/preset-env": "^7.21.5",
    "@babel/runtime": "^7.21.5",
    "@expo/config-plugins": "^6.0.2",
    "@types/babel__core": "^7.20.0",
    "@types/react": "^18.2.8",
    "@types/webpack-env": "^1.18.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.42.0",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

my eas.json

``` json
{
  "cli": {
    "version": ">= 3.3.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium",
        "simulator": true // Only change
      }
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": true,
        "resourceClass": "m-medium"
      }
    },
    "production": {
      "ios": {
        "resourceClass": "m-medium"
      }
    }
  },
  "submit": {
    "production": {}
  }
}

```

### Link to reproduction

https://github.com/AlvaroAquijeDiaz/nosh-now

### To reproduce

1. pnpm i
2. run `eas build --profile development --platform ios` 
3. see logs

**Comment by AlvaroAquijeDiaz** [comment] 2023-06-10 00:16
I think it's also related to #382

**Comment by juliusmarminge** [comment] 2023-06-10 10:04
Duplicate of #393

Upgrade pnpm to the correct version

**Closed by juliusmarminge** 2023-06-10 10:04 UTC

**Comment by AlvaroAquijeDiaz** [comment] 2023-06-10 14:05
@juliusmarminge problem is it's updated on my machine, the logs come from expo.dev, any ideas on how to fix it there?

**Comment by ngnathan** [comment] 2023-06-10 20:41
Same issue here on expo.dev with EAS Build.  I can't find on the docs any support for changing pnpm versions.  

Docs for eas.json schema:
https://docs.expo.dev/build-reference/eas-json/

You can define node and yarn versions, but not pnpm.

**Comment by ngnathan** [comment] 2023-06-10 21:11
Further investigation: Most build images are using `pnpm@7.27.0`.  Because create-t3-turbo uses `pnpm@8.6.1` (right now), the warning says it "might get downgraded to 6.0", which I think it does.  But if you're using `pnpm@7.27.0` the error doesn't show up.

Hopefully EAS sets up some images with an updated pnpm version > 8 for iOS / Android and sets them as default.

For now, the quick workaround I did was to regenerate `pnpm-lock.yaml` from pnpm@7.27.0.
- Delete `pnpm-lock.yaml` (might be tricky if you're already in a production stage app)
- Change your local machine to `pnpm@7.27.0`
- Regenerate pnpm lock file (clean, and then `pnpm install`)
- Then run `eas build` again

If you need something specific for pnpm > 8, then you can run their latest build image for iOS.  Doesn't seem like Android has an option for this though.
- Docs: https://docs.expo.dev/build-reference/infrastructure/
- You would need: [macos-ventura-13.3-xcode-14.3](https://docs.expo.dev/build-reference/infrastructure/#macos-ventura-133-xcode-143-latest-for-apple-silicon-builders-only-available-for-apple-silicon-builders) which has `pnpm@8.2.0`
- Configure eas.json under any `ios` setting to use `"image": "macos-ventura-13.3-xcode-14.3"`.

**Comment by AlvaroAquijeDiaz** [comment] 2023-06-11 17:55
indeed, downgrading the pnpm version seems to make everything work as expected, thanks a lot @ngnathan 🎉
